version: '3.3'
services:
    backend:
        build: 
            context: ./backend
        environment:
            DB_URL: 
            AUTH_SECRET: 
        ports:
            - "3003:3003"
    frontend:
        build: 
            context: ./frontend
        environment: 
            OMDB_API_KEY: 
            AWS_SECRET_KEY: 
            API_ENDPOINT: backend:3003/api
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - backend